/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rit.dietmanager.g1.view;

/**
 *
 * @author lukas
 */

import javax.swing.*;
import java.awt.*;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form view.NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        FoodNameLabel = new javax.swing.JLabel();
        CalioriesLabel = new javax.swing.JLabel();
        FatLabel = new javax.swing.JLabel();
        CarbsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        caltf = new javax.swing.JTextField();
        fattf = new javax.swing.JTextField();
        carbtf = new javax.swing.JTextField();
        addFoodBtn = new javax.swing.JButton();
        RecipeNameLabel = new javax.swing.JLabel();
        FoodNameLabelTwo = new javax.swing.JLabel();
        recipeNametf = new javax.swing.JTextField();
        FoodCount = new javax.swing.JSpinner();
        ProtienLabel = new javax.swing.JLabel();
        proteintf = new javax.swing.JTextField();
        CaloriesTitle = new javax.swing.JLabel();
        DayLabel = new javax.swing.JLabel();
        daytf = new javax.swing.JTextField();
        MonthLabel = new javax.swing.JLabel();
        monthtf = new javax.swing.JTextField();
        YearLabel = new javax.swing.JLabel();
        yeartf = new javax.swing.JTextField();
        setDateBtn = new javax.swing.JButton();
        CaloricIntakeLabel = new javax.swing.JLabel();
        calGoaltf = new javax.swing.JTextField();
        CaloricSetButton = new javax.swing.JButton();
        CurrWeightLabel = new javax.swing.JLabel();
        CurWeightField = new javax.swing.JTextField();
        CurWeightSetButton = new javax.swing.JButton();
        ChangedWeightLabel = new javax.swing.JLabel();
        ChangedWeightField = new javax.swing.JTextField();
        CalorieIntakeLabel = new javax.swing.JLabel();
        tfCal = new javax.swing.JTextField();
        FatIntakeLabel = new javax.swing.JLabel();
        CarbIntakeLabel = new javax.swing.JLabel();
        ProteinIntakeLabel = new javax.swing.JLabel();
        ToDesiredCalLabel = new javax.swing.JLabel();
        tfFat = new javax.swing.JTextField();
        tfCarb = new javax.swing.JTextField();
        tfNeeded = new javax.swing.JTextField();
        tfProtein = new javax.swing.JTextField();
        addnewfoodtext = new javax.swing.JLabel();
        RecipeBuilderLabel = new javax.swing.JLabel();
        firstFoodNametf = new javax.swing.JComboBox<>();
        InstantianteRecipeButton = new javax.swing.JButton();
        AddToRecipeButton = new javax.swing.JButton();
        CreateRecipeButton = new javax.swing.JButton();
        DietMangerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FoodNameLabel.setText("model.Food Name");
        FoodNameLabel.setToolTipText("");

        CalioriesLabel.setText("Calories");

        FatLabel.setText("Fat");

        CarbsLabel.setText("Carbs");

        caltf.setToolTipText("");
        caltf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caltfActionPerformed(evt);
            }
        });

        addFoodBtn.setText("Add model.Food");

        RecipeNameLabel.setText("model.Recipe name");

        FoodNameLabelTwo.setText("Choose food");

        recipeNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeNametfActionPerformed(evt);
            }
        });

        ProtienLabel.setText("Protiens");

        CaloriesTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CaloriesTitle.setText("Calories");

        DayLabel.setText("Day");

        MonthLabel.setText("Month");

        YearLabel.setText("Year");

        setDateBtn.setText("Set");

        CaloricIntakeLabel.setText("Set desired caloric intake");

        CaloricSetButton.setText("Set");

        CurrWeightLabel.setText("Current weight:");

        CurWeightSetButton.setText("Set");

        ChangedWeightLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChangedWeightLabel.setText("Changed weight");

        ChangedWeightField.setEditable(false);
        ChangedWeightField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        CalorieIntakeLabel.setText("Calorie intake");

        tfCal.setEditable(false);
        tfCal.setText("0.0");

        FatIntakeLabel.setText("Fat intake");

        CarbIntakeLabel.setText("Carb intake");

        ProteinIntakeLabel.setText("Protein intake");

        ToDesiredCalLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ToDesiredCalLabel.setText("To desired calorie intake");

        tfFat.setEditable(false);
        tfFat.setText("0.0");

        tfCarb.setEditable(false);
        tfCarb.setText("0.0");

        tfNeeded.setEditable(false);
        tfNeeded.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tfProtein.setEditable(false);
        tfProtein.setText("0.0");

        addnewfoodtext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addnewfoodtext.setText("Add new food");

        RecipeBuilderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RecipeBuilderLabel.setText("model.Recipe builder");

        firstFoodNametf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "model.Food 1", "model.Food 2", "model.Food 3", "model.Food 4" }));

        InstantianteRecipeButton.setText("Instantiante model.Recipe\n");
        InstantianteRecipeButton.setVisible(false);
        InstantianteRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstantianteRecipeButtonActionPerformed(evt);
            }
        });

        AddToRecipeButton.setText("Add to recipe\n");
        AddToRecipeButton.setVisible(false);
        AddToRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToRecipeButtonActionPerformed(evt);
            }
        });

        CreateRecipeButton.setText("Create model.Recipe\n");

        DietMangerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DietMangerLabel.setText("DietManager");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(91, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(503, 503, 503))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(RecipeNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(recipeNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(InstantianteRecipeButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(FoodNameLabelTwo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(firstFoodNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FoodCount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddToRecipeButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(CreateRecipeButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(RecipeBuilderLabel)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(FatLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fattf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CarbsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(carbtf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ProtienLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(proteintf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(CurrWeightLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(CurWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(CurWeightSetButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(CaloricIntakeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(calGoaltf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(CaloricSetButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ChangedWeightLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ChangedWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(CalorieIntakeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfCal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(FatIntakeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfFat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(CarbIntakeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfCarb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ProteinIntakeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ToDesiredCalLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tfNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(176, 176, 176)
                                                .addComponent(FoodNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(CalioriesLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(caltf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(addnewfoodtext))
                                                        .addComponent(DietMangerLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(250, 250, 250)
                                                .addComponent(addFoodBtn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(DayLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(daytf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(MonthLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(CaloriesTitle)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(monthtf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(YearLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(yeartf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(setDateBtn))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(DietMangerLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addnewfoodtext)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FoodNameLabel)
                                        .addComponent(CalioriesLabel)
                                        .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(caltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fattf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FatLabel)
                                        .addComponent(carbtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CarbsLabel)
                                        .addComponent(ProtienLabel)
                                        .addComponent(proteintf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addFoodBtn)
                                .addGap(18, 18, 18)
                                .addComponent(RecipeBuilderLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(recipeNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RecipeNameLabel)
                                        .addComponent(InstantianteRecipeButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FoodNameLabelTwo)
                                        .addComponent(firstFoodNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FoodCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddToRecipeButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CreateRecipeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CaloriesTitle)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DayLabel)
                                        .addComponent(daytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MonthLabel)
                                        .addComponent(monthtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(YearLabel)
                                        .addComponent(yeartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setDateBtn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CaloricIntakeLabel)
                                        .addComponent(calGoaltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CaloricSetButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CurrWeightLabel)
                                        .addComponent(CurWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CurWeightSetButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ChangedWeightLabel)
                                        .addComponent(ChangedWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CalorieIntakeLabel)
                                        .addComponent(tfCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FatIntakeLabel)
                                        .addComponent(tfFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CarbIntakeLabel)
                                        .addComponent(tfCarb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ProteinIntakeLabel)
                                        .addComponent(tfProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ToDesiredCalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void caltfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void InstantianteRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void AddToRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void recipeNametfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.model.Logger.getLogger(view.NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.model.Logger.getLogger(view.NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.model.Logger.getLogger(view.NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.model.Logger.getLogger(view.NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new view.NewJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
    private javax.swing.JButton AddToRecipeButton;
    private javax.swing.JLabel CalioriesLabel;
    private javax.swing.JLabel CaloricIntakeLabel;
    private javax.swing.JButton CaloricSetButton;
    private javax.swing.JLabel CalorieIntakeLabel;
    private javax.swing.JLabel CaloriesTitle;
    private javax.swing.JLabel CarbIntakeLabel;
    private javax.swing.JLabel CarbsLabel;
    private javax.swing.JTextField ChangedWeightField;
    private javax.swing.JLabel ChangedWeightLabel;
    private javax.swing.JButton CreateRecipeButton;
    private javax.swing.JTextField CurWeightField;
    private javax.swing.JButton CurWeightSetButton;
    private javax.swing.JLabel CurrWeightLabel;
    private javax.swing.JLabel DayLabel;
    private javax.swing.JLabel DietMangerLabel;
    private javax.swing.JLabel FatIntakeLabel;
    private javax.swing.JLabel FatLabel;
    private javax.swing.JSpinner FoodCount;
    private javax.swing.JLabel FoodNameLabel;
    private javax.swing.JLabel FoodNameLabelTwo;
    private javax.swing.JButton InstantianteRecipeButton;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JLabel ProteinIntakeLabel;
    private javax.swing.JLabel ProtienLabel;
    private javax.swing.JLabel RecipeBuilderLabel;
    private javax.swing.JLabel RecipeNameLabel;
    private javax.swing.JLabel ToDesiredCalLabel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JButton addFoodBtn;
    private javax.swing.JLabel addnewfoodtext;
    private javax.swing.JTextField calGoaltf;
    private javax.swing.JTextField caltf;
    private javax.swing.JTextField carbtf;
    private javax.swing.JTextField daytf;
    private javax.swing.JTextField fattf;
    private javax.swing.JComboBox<String> firstFoodNametf;
    private javax.swing.JTextField firstFoodCount;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField monthtf;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField proteintf;
    private javax.swing.JTextField recipeNametf;
    private javax.swing.JButton setDateBtn;
    private javax.swing.JTextField tfCal;
    private javax.swing.JTextField tfCarb;
    private javax.swing.JTextField tfFat;
    private javax.swing.JTextField tfNeeded;
    private javax.swing.JTextField tfProtein;
    private javax.swing.JTextField yeartf;
    // End of variables declaration

    public void clearFoodInputs() {
        this.nametf.setText("");
        this.caltf.setText("");
        this.fattf.setText("");
        this.carbtf.setText("");
        this.proteintf.setText("");
    }

    public void updateEatFood(String[] food) {
        DefaultComboBoxModel newDropdown = new DefaultComboBoxModel(food);
        firstFoodNametf.removeAllItems();
        firstFoodNametf.setModel(newDropdown);
    }

    public void clearCalorieInput() {
        this.calGoaltf.setText("");
    }

    public void clearRecipeInputs(){
        this.recipeNametf.setText("");
        this.FoodCount.setValue(0);
    }

    public JFrame f = new JFrame();

    public void dialogError(String message) {
        JOptionPane.showMessageDialog(f, message);
    }

    public JButton getFoodBtn() {
        return addFoodBtn;
    }

    public JButton getRecipeBtn() {
        return AddToRecipeButton;
    }

    public JButton getCalorieBtn() {
        return CaloricSetButton;
    }

    public JButton getCurrentWeightBtn() {
        return CurWeightSetButton;
    }

    public JButton getDateBtn() {
        return setDateBtn;
    }

    public String getFoodName() {
        return nametf.getText();
    }

    public String getFoodCal() {
        return caltf.getText();
    }

    public String getFoodFat() {
        return fattf.getText();
    }

    public String getFoodCarb() {
        return carbtf.getText();
    }

    public String getFoodProtein() {
        return proteintf.getText();
    }

    public String getCalorieIntake() {
        return calGoaltf.getText();
    }

    public String getSelectedFoodToBeEaten() {
        return (String) this.firstFoodNametf.getItemAt(firstFoodNametf.getSelectedIndex());
    }

    public String getServings() {
        return this.FoodCount.getValue().toString();
    }

    public JComboBox<String> getFoodNameTF(){
        return firstFoodNametf;
    }

    public String getFoodCountTF() {
        return FoodCount.getValue().toString();
    }

    public String getRecipeNameTF() {
        return recipeNametf.getText();
    }

    public JTextField getCalIntakeTF() {
        return tfCal;
    }

    public JTextField getFatIntakeTF() {
        return tfFat;
    }

    public JTextField getCarbIntakeTF() {
        return tfCarb;
    }

    public JTextField getProteinIntakeTF() {
        return tfProtein;
    }

    public JButton getSelectEatenB() {
        return AddToRecipeButton;
    }

    public String getDay() {
        return daytf.getText();
    }

    public String getMonth() {
        return monthtf.getText();
    }

    public String getYear() {
        return yeartf.getText();
    }

    public JButton getInstantiateRecipeButton(){
        return InstantianteRecipeButton;
    }

    public JButton getCreateRecipeButton(){
        return CreateRecipeButton;
    }

}
